// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: v1/rates.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateCalcMethod int32

const (
	RateCalcMethod_RATE_CALC_METHOD_UNSPECIFIED RateCalcMethod = 0
	RateCalcMethod_RATE_CALC_METHOD_TOP_N       RateCalcMethod = 1
	RateCalcMethod_RATE_CALC_METHOD_AVG_NM      RateCalcMethod = 2
)

// Enum value maps for RateCalcMethod.
var (
	RateCalcMethod_name = map[int32]string{
		0: "RATE_CALC_METHOD_UNSPECIFIED",
		1: "RATE_CALC_METHOD_TOP_N",
		2: "RATE_CALC_METHOD_AVG_NM",
	}
	RateCalcMethod_value = map[string]int32{
		"RATE_CALC_METHOD_UNSPECIFIED": 0,
		"RATE_CALC_METHOD_TOP_N":       1,
		"RATE_CALC_METHOD_AVG_NM":      2,
	}
)

func (x RateCalcMethod) Enum() *RateCalcMethod {
	p := new(RateCalcMethod)
	*p = x
	return p
}

func (x RateCalcMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateCalcMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_rates_proto_enumTypes[0].Descriptor()
}

func (RateCalcMethod) Type() protoreflect.EnumType {
	return &file_v1_rates_proto_enumTypes[0]
}

func (x RateCalcMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateCalcMethod.Descriptor instead.
func (RateCalcMethod) EnumDescriptor() ([]byte, []int) {
	return file_v1_rates_proto_rawDescGZIP(), []int{0}
}

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        RateCalcMethod         `protobuf:"varint,1,opt,name=method,proto3,enum=v1.RateCalcMethod" json:"method,omitempty"`
	N             uint32                 `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	M             uint32                 `protobuf:"varint,3,opt,name=m,proto3" json:"m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_v1_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_v1_rates_proto_rawDescGZIP(), []int{0}
}

func (x *GetRatesRequest) GetMethod() RateCalcMethod {
	if x != nil {
		return x.Method
	}
	return RateCalcMethod_RATE_CALC_METHOD_UNSPECIFIED
}

func (x *GetRatesRequest) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *GetRatesRequest) GetM() uint32 {
	if x != nil {
		return x.M
	}
	return 0
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           float64                `protobuf:"fixed64,1,opt,name=ask,proto3" json:"ask,omitempty"`
	Bid           float64                `protobuf:"fixed64,2,opt,name=bid,proto3" json:"bid,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_v1_rates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_v1_rates_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatesResponse) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *GetRatesResponse) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *GetRatesResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

var File_v1_rates_proto protoreflect.FileDescriptor

const file_v1_rates_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/rates.proto\x12\x02v1\"Y\n" +
	"\x0fGetRatesRequest\x12*\n" +
	"\x06method\x18\x01 \x01(\x0e2\x12.v1.RateCalcMethodR\x06method\x12\f\n" +
	"\x01n\x18\x02 \x01(\rR\x01n\x12\f\n" +
	"\x01m\x18\x03 \x01(\rR\x01m\"]\n" +
	"\x10GetRatesResponse\x12\x10\n" +
	"\x03ask\x18\x01 \x01(\x01R\x03ask\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\x01R\x03bid\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix*k\n" +
	"\x0eRateCalcMethod\x12 \n" +
	"\x1cRATE_CALC_METHOD_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RATE_CALC_METHOD_TOP_N\x10\x01\x12\x1b\n" +
	"\x17RATE_CALC_METHOD_AVG_NM\x10\x022D\n" +
	"\vRateService\x125\n" +
	"\bGetRates\x12\x13.v1.GetRatesRequest\x1a\x14.v1.GetRatesResponseB7Z5github.com/GGnet123/tech_assignment_nanaban/pkg/pb/v1b\x06proto3"

var (
	file_v1_rates_proto_rawDescOnce sync.Once
	file_v1_rates_proto_rawDescData []byte
)

func file_v1_rates_proto_rawDescGZIP() []byte {
	file_v1_rates_proto_rawDescOnce.Do(func() {
		file_v1_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_rates_proto_rawDesc), len(file_v1_rates_proto_rawDesc)))
	})
	return file_v1_rates_proto_rawDescData
}

var file_v1_rates_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_rates_proto_goTypes = []any{
	(RateCalcMethod)(0),      // 0: v1.RateCalcMethod
	(*GetRatesRequest)(nil),  // 1: v1.GetRatesRequest
	(*GetRatesResponse)(nil), // 2: v1.GetRatesResponse
}
var file_v1_rates_proto_depIdxs = []int32{
	0, // 0: v1.GetRatesRequest.method:type_name -> v1.RateCalcMethod
	1, // 1: v1.RateService.GetRates:input_type -> v1.GetRatesRequest
	2, // 2: v1.RateService.GetRates:output_type -> v1.GetRatesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_rates_proto_init() }
func file_v1_rates_proto_init() {
	if File_v1_rates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_rates_proto_rawDesc), len(file_v1_rates_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_rates_proto_goTypes,
		DependencyIndexes: file_v1_rates_proto_depIdxs,
		EnumInfos:         file_v1_rates_proto_enumTypes,
		MessageInfos:      file_v1_rates_proto_msgTypes,
	}.Build()
	File_v1_rates_proto = out.File
	file_v1_rates_proto_goTypes = nil
	file_v1_rates_proto_depIdxs = nil
}
